# Site settings
title: PITPLE
email: biz@pitple.com
description: PITPLE Inc. Homepage
baseurl: "/jekyll-pitple" # the subpath of your site, e.g. 
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
timezone: Asia/Seoul
markdown: kramdown

exclude: [.gitignore, README.md, publish.sh]
include: [.nojekyll]

# Gems
gems:
  - github-pages
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["en", "ko"]
exclude_from_localizations: ["javascript", "images", "css"]